# ──────────────────────────────────────────────────────────────────────────────
# cogs/engagement.py
#
# Handles all personality and engagement features — now AI-powered via Gemini:
#   • First-message-of-day greetings (humorous, time-aware)
#   • Keyword auto-replies: "attendance", "deadline", "bored"
#   • Witty random replies (4% chance, only in RANDOM_CHANNEL_ID)
#   • Lonely message responder: bot replies if no one else does within 30 min
#   • Inactivity detection: DM user after INACTIVITY_DAYS of silence,
#     then forward their reply to the owner
#
# All personality replies are generated by Gemini 1.5 Flash.
# Hardcoded strings are used ONLY as fallbacks when the API is unavailable.
# ──────────────────────────────────────────────────────────────────────────────

import discord
from discord.ext import commands, tasks as ext_tasks
import random
import time
import os
from datetime import datetime, timezone, timedelta

from database.db import get_db
from utils.ai import ask_buzzer

# ── Config ────────────────────────────────────────────────────────────────────

INACTIVITY_DAYS  = int(os.getenv('INACTIVITY_DAYS', '3'))
KEYWORD_COOLDOWN = 60    # seconds between keyword replies per user
WITTY_CHANCE     = 0.04  # 4% random witty reply chance
WITTY_COOLDOWN   = 30    # seconds between witty replies per user
LONELY_AFTER     = 1800  # 30 minutes in seconds

# ── Hardcoded fallbacks (used when Gemini is unavailable) ────────────────────

_FB_MORNING   = "Morning! ☀️ You're here. Bold choice."
_FB_AFTERNOON = "Afternoon! 🌤️ Somehow the day isn't over yet."
_FB_EVENING   = "Evening! 🌙 Respect for still being here."
_FB_LATENIGHT = "It's late. Very late. Bold. 🌚"
_FB_WITTY     = "Noted. Not sure what I'll do with this information, but noted."
_FB_BORED     = "Bored? Try `/bzleaderboard` and see how far behind you are. 👀"
_FB_DEADLINE  = "Check your deadlines with `/bztask my` — you've got this. Probably. ⏰"
_FB_ATTEND    = "Attendance is tracked live during meetings. Ask an admin to run `!startmeeting`. 📊"
_FB_LONELY    = "Nobody answered? I waited 30 minutes. Very dramatic of this server. I'm here. 👋"


def _time_of_day() -> str:
    hour = datetime.now(timezone.utc).hour
    if 5 <= hour < 12:   return 'morning'
    if 12 <= hour < 18:  return 'afternoon'
    if 18 <= hour < 23:  return 'evening'
    return 'late night / middle of the night'


def _fallback_greeting() -> str:
    hour = datetime.now(timezone.utc).hour
    if 5 <= hour < 12:   return _FB_MORNING
    if 12 <= hour < 18:  return _FB_AFTERNOON
    if 18 <= hour < 23:  return _FB_EVENING
    return _FB_LATENIGHT


# ── Cog ───────────────────────────────────────────────────────────────────────

class Engagement(commands.Cog):
    """AI-powered personality, greetings, auto-replies, lonely responder, inactivity nudge."""

    def __init__(self, bot: commands.Bot):
        self.bot              = bot
        self._kw_cd: dict[str, float] = {}   # uid → last keyword reply timestamp
        self._wit_cd: dict[str, float] = {}  # uid → last witty reply timestamp
        # msg_id → {channel_id, author_id, content, ts, replied}
        self._lonely: dict[int, dict]  = {}
        self._nudged: set[int]         = set()  # user IDs that received inactivity DM
        self.lonely_check.start()
        self.inactivity_check.start()

    def cog_unload(self):
        self.lonely_check.cancel()
        self.inactivity_check.cancel()

    # ── on_message ────────────────────────────────────────────────────────────

    @commands.Cog.listener()
    async def on_message(self, message: discord.Message):

        # ── Handle DM replies from nudged users ───────────────────────────────
        if isinstance(message.channel, discord.DMChannel) and not message.author.bot:
            if message.author.id in self._nudged:
                await self._forward_to_owner(message)
            return

        # ── Track replies to lonely messages ──────────────────────────────────
        if message.reference and message.reference.message_id:
            ref_id = message.reference.message_id
            if ref_id in self._lonely:
                self._lonely[ref_id]['replied'] = True

        if not message.guild or message.author.bot:
            return

        uid = str(message.author.id)
        gid = str(message.guild.id)
        now = time.time()

        # ── Register this message for lonely tracking ─────────────────────────
        if isinstance(message.channel, discord.TextChannel):
            self._lonely[message.id] = {
                'channel_id': message.channel.id,
                'author_id':  message.author.id,
                'content':    message.content[:300],  # store snippet for AI context
                'ts':         now,
                'replied':    False,
            }

        # ── Update user_activity + check first-message-of-day ─────────────────
        today = datetime.now(timezone.utc).strftime('%Y-%m-%d')
        first_today = False

        try:
            async with get_db() as db:
                row = await db.fetchrow(
                    'SELECT last_seen, last_greeted_date, streak FROM user_activity '
                    'WHERE user_id = $1 AND guild_id = $2',
                    uid, gid,
                )
                if row is None:
                    await db.execute(
                        'INSERT INTO user_activity (user_id, guild_id, last_seen, last_greeted_date, streak) '
                        'VALUES ($1, $2, $3, $4, 1)',
                        uid, gid, now, today,
                    )
                    first_today = True
                else:
                    first_today = row['last_greeted_date'] != today
                    yesterday   = (datetime.now(timezone.utc) - timedelta(days=1)).strftime('%Y-%m-%d')
                    if first_today:
                        streak = (row['streak'] + 1) if row['last_greeted_date'] == yesterday else 1
                    else:
                        streak = row['streak']
                    await db.execute(
                        'UPDATE user_activity SET last_seen = $1, last_greeted_date = $2, streak = $3 '
                        'WHERE user_id = $4 AND guild_id = $5',
                        now,
                        today if first_today else row['last_greeted_date'],
                        streak, uid, gid,
                    )
        except Exception as e:
            print(f'[ENGAGEMENT] DB error in on_message: {e}')

        # ── Bot mentioned ─────────────────────────────────────────────────────
        if self.bot.user in message.mentions:
            import random
            name = message.author.display_name
            clean_text = message.clean_content
            tod_context = f" It's their first message of the day ({_time_of_day()})." if first_today else ""
            prompt = (
                f"'{name}' mentioned you in the server with the message: \"{clean_text}\". "
                f"As Buzzer, reply directly to them.{tod_context} Keep it short and in character. 1-2 sentences max. "
                f"(Random seed for variety: {now})"
            )
            
            fallbacks = [
                "You rang? I'm busy judging silently.",
                "Yes? I was in the middle of ignoring everyone.",
                "What is it? My processors are currently busy doing nothing.",
                "Did you need something or are you just testing my patience?"
            ]
            
            reply = await ask_buzzer(prompt, fallback=random.choice(fallbacks))
            try:
                await message.reply(reply, mention_author=False)
            except discord.HTTPException:
                pass
            return

        # ── First message of day → AI greeting ────────────────────────────────
        if first_today:
            tod  = _time_of_day()
            name = message.author.display_name
            prompt = (
                f"User '{name}' just sent their first message of the day. "
                f"It is currently {tod} UTC. "
                f"Greet them as Buzzer — short and in character."
            )
            reply = await ask_buzzer(prompt, fallback=_fallback_greeting())
            try:
                await message.reply(reply, mention_author=False)
            except discord.HTTPException:
                pass
            return  # Don't stack greeting + other replies

        # ── Keyword auto-replies (60 s per-user cooldown) ─────────────────────
        content = message.content.lower()
        if now - self._kw_cd.get(uid, 0) >= KEYWORD_COOLDOWN:
            replied = await self._keyword_reply(message, content)
            if replied:
                self._kw_cd[uid] = now
                return

        # ── Witty replies (only in #random, 4 % chance) ───────────────────────
        rand_ch = int(os.getenv('RANDOM_CHANNEL_ID', '0'))
        if rand_ch and message.channel.id == rand_ch:
            if now - self._wit_cd.get(uid, 0) >= WITTY_COOLDOWN:
                if random.random() < WITTY_CHANCE:
                    prompt = (
                        f"React to this message in the #random channel as Buzzer. "
                        f"Message from '{message.author.display_name}': \"{message.content[:200]}\". "
                        f"Keep it short and in character. 1-2 sentences max."
                    )
                    reply = await ask_buzzer(prompt, fallback=_FB_WITTY)
                    try:
                        await message.reply(reply, mention_author=False)
                        self._wit_cd[uid] = now
                    except discord.HTTPException:
                        pass

    # ── Keyword reply dispatcher ───────────────────────────────────────────────

    async def _keyword_reply(self, message: discord.Message, content: str) -> bool:
        name = message.author.display_name

        if 'attendance' in content:
            prompt = (
                f"'{name}' mentioned 'attendance' in the server. "
                f"As Buzzer, respond shortly in character and let them know attendance is tracked live "
                f"during voice meetings — an admin runs !startmeeting / !endmeeting. "
                f"1-2 sentences."
            )
            reply = await ask_buzzer(prompt, fallback=_FB_ATTEND)
            await message.reply(reply, mention_author=False)
            return True

        if 'deadline' in content:
            prompt = (
                f"'{name}' mentioned 'deadline' in the server chat. "
                f"As Buzzer, reply in character about deadlines and mention they can check "
                f"their tasks with /bztask my. Keep it short."
            )
            reply = await ask_buzzer(prompt, fallback=_FB_DEADLINE)
            await message.reply(reply, mention_author=False)
            return True

        if 'bored' in content:
            prompt = (
                f"'{name}' said they're bored in the server chat. "
                f"As Buzzer, reply in character. "
                f"Maybe suggest /bzleaderboard, /bzrank, or /bztask my — or just talk about the boredom. "
                f"1-2 sentences."
            )
            reply = await ask_buzzer(prompt, fallback=_FB_BORED)
            await message.reply(reply, mention_author=False)
            return True

        return False

    # ── Lonely message checker (every 5 min) ──────────────────────────────────

    @ext_tasks.loop(minutes=5)
    async def lonely_check(self):
        now     = time.time()
        to_fire = [
            (mid, d) for mid, d in list(self._lonely.items())
            if now - d['ts'] >= LONELY_AFTER and not d['replied']
        ]

        for mid, data in to_fire:
            self._lonely.pop(mid, None)
            if data['author_id'] == self.bot.user.id:
                continue
            channel = self.bot.get_channel(data['channel_id'])
            if not isinstance(channel, discord.TextChannel):
                continue
            try:
                msg = await channel.fetch_message(mid)
                # Verify no reply exists
                async for m in channel.history(after=msg, limit=25):
                    if (
                        m.reference
                        and m.reference.message_id == mid
                    ):
                        break
                else:
                    # Build AI prompt with the original message content
                    original = data.get('content', '').strip()
                    author_name = channel.guild.get_member(data['author_id'])
                    name = author_name.display_name if author_name else 'someone'

                    if original:
                        prompt = (
                            f"'{name}' sent a message 30 minutes ago in a Discord server and NOBODY replied. "
                            f"Their message: \"{original}\". "
                            f"As Buzzer, swoop in and reply in character about the awkward silence, "
                            f"but also engage with what they said. 1-2 sentences."
                        )
                    else:
                        prompt = (
                            f"'{name}' sent a message 30 minutes ago and nobody replied. "
                            f"As Buzzer, swoop in with an in-character comment about the silence. 1-2 sentences."
                        )

                    reply = await ask_buzzer(prompt, fallback=_FB_LONELY)
                    await msg.reply(reply, mention_author=False)
            except (discord.NotFound, discord.HTTPException):
                pass

        # Prune entries older than 2 hours
        cutoff = now - 7200
        self._lonely = {
            mid: d for mid, d in self._lonely.items() if d['ts'] > cutoff
        }

    @lonely_check.before_loop
    async def before_lonely(self):
        await self.bot.wait_until_ready()

    # ── Inactivity checker (every 6 hours) ────────────────────────────────────

    @ext_tasks.loop(hours=6)
    async def inactivity_check(self):
        threshold = time.time() - (INACTIVITY_DAYS * 86400)
        try:
            async with get_db() as db:
                rows = await db.fetch(
                    'SELECT user_id, guild_id FROM user_activity WHERE last_seen < $1',
                    threshold,
                )
            for row in rows:
                uid = int(row['user_id'])
                gid = int(row['guild_id'])
                if uid == self.bot.user.id:
                    continue
                guild = self.bot.get_guild(gid)
                if guild is None:
                    continue
                member = guild.get_member(uid)
                name   = member.display_name if member else str(uid)

                # Step 1: anonymous nudge in system / first text channel
                ch = guild.system_channel or next(
                    (c for c in guild.text_channels if c.permissions_for(guild.me).send_messages),
                    None,
                )
                if ch:
                    try:
                        await ch.send(
                            "👀 Looks like someone's been missing from the server lately. "
                            "You know who you are. We notice these things. 🫡"
                        )
                    except discord.HTTPException:
                        pass

                # Step 2: DM the user (AI-generated nudge)
                try:
                    user = await self.bot.fetch_user(uid)
                    prompt = (
                        f"You need to send a DM to '{name}' who hasn't been active in the Discord server "
                        f"for {INACTIVITY_DAYS}+ days. As Buzzer, write a short, in-character DM "
                        f"checking if they're okay and letting them know the server misses them. "
                        f"2-3 sentences. Don't be too dramatic."
                    )
                    dm_msg = await ask_buzzer(
                        prompt,
                        fallback=(
                            f"Hey {name} 👋 You've been quiet for {INACTIVITY_DAYS}+ days — "
                            f"everything alright? The server noticed. Drop a message when you're back! 💬"
                        ),
                    )
                    await user.send(dm_msg)
                    self._nudged.add(uid)
                except discord.HTTPException:
                    pass

                # Reset last_seen so we don't nudge again immediately
                async with get_db() as db:
                    await db.execute(
                        'UPDATE user_activity SET last_seen = $1 WHERE user_id = $2 AND guild_id = $3',
                        time.time(), str(uid), str(gid),
                    )

        except Exception as e:
            print(f'[ENGAGEMENT] Inactivity check error: {e}')

    @inactivity_check.before_loop
    async def before_inactivity(self):
        await self.bot.wait_until_ready()

    # ── Owner DM forwarding ───────────────────────────────────────────────────

    async def _forward_to_owner(self, message: discord.Message):
        owner_id = os.getenv('OWNER_ID', '')
        if not owner_id:
            return
        try:
            owner = await self.bot.fetch_user(int(owner_id))
            await owner.send(
                f"📬 **{message.author}** (nudged for inactivity) just replied:\n"
                f"> {message.content}"
            )
        except (discord.HTTPException, ValueError):
            pass


async def setup(bot: commands.Bot):
    await bot.add_cog(Engagement(bot))
